### ISSUE TITLE
Using submodules to track internal dependencies

### ISSUE THREAD

**Issue by leonardt** [StanfordAHA/CGRAFlow#22]
Requested by @cdonovick 

@jameshegarty, @phanrahan, and I had discussed using submodules. Our main concern was that they would require an explicit PR to bump the submodule commit whenever a repo pushed changes to master. If the person responsible for initiating this PR did not do it, the flow could be silently broken (that is, if they had bumped the submodule commit, we would've seen the flow break). In our current model, the nightly run would catch an offending master branch that has broken the flow, so if we have a silent breakage, at least it only lasts less than 24 hours.

Using submodules could work, but I believe it would require that we institute and enforce a policy that any changes to a master branch be accompanied by a PR to bump the submodule commit in the CGRAFlow repo. 

I'd be open to hearing other solutions that prevent the flow from being broken silently.

**Comment by cdonovick** [comment]
I had forgotten about the whole not being able to always point to HEAD in a submodule so I wan to retract that request.  We could potentially use subtrees https://github.com/apenwarr/git-subtree/
