### ISSUE TITLE
Flow is broken

### ISSUE THREAD

**Issue by cdonovick** [StanfordAHA/CGRAFlow#26]
Appears to be the results of changes to CGRAGenerator on august 14

**Comment by steveri** [comment]
This is a result of Artem's recent changes I think.  I sent him mail a couple of days ago but have not yet heard back.  Meanwhile I recommend changing the travis script / makefile to use a pre-change version of CGRAGenerator...which I guess would be...856b4c2a36c128e84b378a106ea265e4510cb315...from Aug 14 ish.

I would try and fix it myself but unfortunately won't have much time before next Monday...

**Comment by cdonovick** [comment]
I will move all commits post 856b4c2a36c128e84b378a106ea265e4510cb315 to a dev branch, and revert master

**Comment by cdonovick** [comment]
I have moved all commits post `856b4c2a36c128e84b378a106ea265e4510cb315` to branch `broken`.
