### ISSUE TITLE
Merging CoreIR Dev into Master

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/CGRAFlow#28]
Due to: https://github.com/rdaly525/coreir/pull/161 

CoreIR Dev (Lots and lots of new features and a few API changes)
is being merged into master. This will definitely affect @jeffsetter and myself (mapper) and might affect @cdonovick 

@jeffsetter, @cdonovick Can you both get your stuff working with coreir dev branch?

**Comment by leonardt** [comment]
@cdonovick After a quick review of the changes, I believe the only interface change to the Python bindings is `get_config_value` -> `config[value]`, the rest should be feature additions.

**Comment by cdonovick** [comment]
I think we can close this issue
