### ISSUE TITLE
Move apt packages back to .travis.yml

### ISSUE THREAD

**Issue by cdonovick** [StanfordAHA/CGRAFlow#29]
Because apt requirements are not listed in `.travis.yml` but instead in `install.sh` we lose out on the ability to cache apt packages.

**Comment by jameshegarty** [comment]
Do you mean that the packages need to be listed in addons:apt:packages: for this to work?

**Comment by cdonovick** [comment]
I believe so

**Comment by jameshegarty** [comment]
I tried doing this, but it didn't change the travis runtime. Given that, I suggest we just stay with the current setup, since it is more generally useful.

Maybe I did something wrong... if you want to try it yourself look at checkout ab07f35508442fe6127800c2e8bbe1a70e4dc11c
