### ISSUE TITLE
Halide -> test all outputs in coreir

### ISSUE THREAD

**Issue by leonardt** [StanfordAHA/CGRAFlow#48]
- [ ] Test coreir output of halide compiler using simulation or formal verification (against x86 halide backend)

**Comment by jeffsetter** [comment]
All coreir_examples and coreir_tests using the simulator (coreir interpreter) to compute images and check against Halide's x86 backend.

https://github.com/jeffsetter/Halide_CoreIR/commit/eeef8b7187c8841a69670bc2dbdfe674b0a5f28b
