### ISSUE TITLE
CoreIR now has a real library and include interface. Will break Jeff's code. 

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/CGRAFlow#7]
Jeff, please create a branch for your stuff and then verify using the coreir/libreorg branch of CGRAFlow

items that will likely need to be fixed:

Add to Makefile:
  Add -lcoreir  -lcoreir-stdlib -lcoreir-passes (Make sure to add at END of command)
  Add -L<Path to coreir/bin>
  Add -I<Path to coreir/incldue>

change getStdlib -> CoreIRLoadLibrary_stdlib
Look at one of my tests (coreir/tests/unit/*.cpp) to see how to redo your includes for cpp/hpp files

**Comment by jeffsetter** [comment]
After downloading a clean copy of coreir and moving to the libreorg branch, I'm having a problem after "make install" with "make test." Below is the error:

build/ctest: error while loading shared libraries: libcoreir-c.so: cannot open shared object file: No such file or directory

**Comment by rdaly525** [comment]
@jeffsetter, Sorry I also forgot to mention that you need to point your LD_LIBRARY_PATH to coreir/bin (or if you are on mac, point DYLD_LIBRARY_PATH)

**Comment by jeffsetter** [comment]
Could we instead use -rpath? Something like this, so I don't have to add to my LD_LIBRARY_PATH?

LIBS = -Wl,-rpath=$(BIN) -lcoreir-stdlib -lcoreir-passes -lcoreir

**Comment by rdaly525** [comment]
@jeffsetter I do not know how to get this to work for both OSX and Linux. If you have any ideas on how to get it to work, can you stop by?

**Comment by rdaly525** [comment]
@jeffsetter, just pushed the update to use rpath instead

**Comment by rdaly525** [comment]
@steveri, @nikhilbhagdikar  I am unsure of what the bug is here. Could you take a look at this log? https://travis-ci.org/StanfordAHA/CGRAFlow/jobs/226615471 

The changes we did ideally should not have affected anything with the cgra/testbench generator.

**Comment by steveri** [comment]
OMG I'm so sorry I can't believe I didn't check my mail since Thu evening!
Anyway, I'm pretty sure this is the test.py problem that I just sent mail to Caleb about (I think you (Ross) got cc'ed, yes?)
Steve

**Comment by jeffsetter** [comment]
I just reran Build #227 on travis (as referenced above) and it appears to work. Is this resolved and can be merged into master?

**Comment by rdaly525** [comment]
Closing this. Fixed by #8
