### ISSUE TITLE
Create a list of inefficient hardware mappings

### ISSUE THREAD

**Issue by priyanka-raina** [StanfordAHA/CGRAFlow#76]

**Comment by jeffsetter** [comment]
The mapper is not utilizing all available operators on the CGRA efficiently:
less than, greater than - currently using two operators (less than: gte -> not;   greater than: lte -> not)
    should be implemented using 1 CGRA tile using 1-bit flags
max, min - currently using two operators (min: lte -> mux;   max: gte -> mux)
   should be implemented using 1 CGRA tile (alu op code 4,5)
counter - currently using six instances (reg, 2 const, ult, add, or)
   should be implemented using a CGRA-specific mapping
abs - currently using five instances (mux, sge, mul, 2 const)
   should be implemented using 1 CGRA tile (alu op code 3)

CGRA spec: https://github.com/StanfordAHA/CGRAGenerator/wiki/PE-Spec

**Comment by jeffsetter** [comment]
less than, greater than, max, min, abs
all are mapping correctly now.
Counter does not exist in hardware, so mapping is doing as well as possible.
